apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: demo-issuing-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /issue
spec:
  ingressClassName: nginx
  rules:
  - host: cloud-wallet.xfsc.dev
    http:
      paths:
      - path: /issuing-demo/issue
        pathType: Prefix
        backend:
          service:
            name: demo-nats-services
            port:
              number: 8070
  tls:
  - hosts:
      - cloud-wallet.xfsc.dev
    secretName: xfsc-wildcard

