update:
	docker build -f issuing.Dockerfile -t node-654e3bca7fbeeed18f81d7c7.ps-xaas.io/pcm-cloud/issuing:demo .
	docker push node-654e3bca7fbeeed18f81d7c7.ps-xaas.io/pcm-cloud/issuing:demo
	docker build -f presentation.Dockerfile -t node-654e3bca7fbeeed18f81d7c7.ps-xaas.io/pcm-cloud/presentation:demo .
	docker push node-654e3bca7fbeeed18f81d7c7.ps-xaas.io/pcm-cloud/presentation:demo

update-presentation:
	docker build -f presentation.Dockerfile -t node-654e3bca7fbeeed18f81d7c7.ps-xaas.io/pcm-cloud/presentation:demo .
	docker push node-654e3bca7fbeeed18f81d7c7.ps-xaas.io/pcm-cloud/presentation:demo

update-issuing:
    docker build -f issuing.Dockerfile -t node-654e3bca7fbeeed18f81d7c7.ps-xaas.io/pcm-cloud/issuing:demo .
    docker push node-654e3bca7fbeeed18f81d7c7.ps-xaas.io/pcm-cloud/issuing:demo