apiVersion: v2
appVersion: v1.0.0
description: Demo Nats Services
name: demo-nats-services
version: 1.0.1
dependencies:
  - name: library
    version: 1.1.1
    repository: oci://node-654e3bca7fbeeed18f81d7c7.ps-xaas.io/dev-ops