# Default values for demo-nats-services.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

service:
  type: ClusterIP

autoscaling:
  enabled: false

image:
  repository: node-654e3bca7fbeeed18f81d7c7.ps-xaas.io/pcm-cloud
  pullPolicy: Always
  presentation:
    name: presentation
    tag: demo
  issuing:
    name: issuing
    tag: demo
  # Overrides the image tag whose default is the chart appVersion.

ingress:
  enabled: true
  host: cloud-wallet.xfsc.dev
  annotations:
    nginx.org/client-max-body-size: 2K #Maximum Size of Credentials which are uploadable
    nginx.ingress.kubernetes.io/rewrite-target: $2


config:
  nats:
    url: nats.nats.svc.cluster.local:4222

  presentation:
    port: 8080

  issuing:
    port: 8070
