version: "3.7"
services:
  fed1-dns:
    image: node-654e3bca7fbeeed18f81d7c7.ps-xaas.io/train/dns-zone-manager-nsd:master
    container_name: fed1-dns
    ports:
      - 16001:16001
    volumes:
      - fed1-zonedata:/var/lib/zonemgr
      - ./config/zonemanager.conf:/usr/lib/zonemgr/config.conf
      - ./config/zonemanagerAuth.conf:/usr/lib/zonemgr/auth.conf
    networks:
      train:
        ipv4_address: 172.30.1.1

volumes:
  fed1-zonedata:
    name: fed1-zonedata

networks:
  train:
    external: false
    name: train
    ipam:
      config:
        - subnet: 172.30.0.1/16